include(mingl/mingl.pri)
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        Maxime/main.cpp \
        TP8/MinGL2/examples/00-Boilerplate/main.cpp \
        TP8/MinGL2/examples/01-Shapes/main.cpp \
        TP8/MinGL2/examples/02-Texte/main.cpp \
        TP8/MinGL2/examples/03-Clavier/main.cpp \
        TP8/MinGL2/examples/04-Souris/main.cpp \
        TP8/MinGL2/examples/05-Transition/main.cpp \
        TP8/MinGL2/examples/06-Sprite/main.cpp \
        TP8/MinGL2/examples/07-Audio/main.cpp \
        TP8/MinGL2/examples/08-CustomDrawable/bgtext.cpp \
        TP8/MinGL2/examples/08-CustomDrawable/main.cpp \
        TP8/MinGL2/examples/09-CustomTransitionable/bgtext.cpp \
        TP8/MinGL2/examples/09-CustomTransitionable/main.cpp \
        TP8/MinGL2/src/audio/audioengine.cpp \
        TP8/MinGL2/src/event/event_manager.cpp \
        TP8/MinGL2/src/exception/cexception.cpp \
        TP8/MinGL2/src/graphics/rgbacolor.cpp \
        TP8/MinGL2/src/graphics/vec2d.cpp \
        TP8/MinGL2/src/gui/glut_font.cpp \
        TP8/MinGL2/src/gui/sprite.cpp \
        TP8/MinGL2/src/gui/text.cpp \
        TP8/MinGL2/src/mingl.cpp \
        TP8/MinGL2/src/shape/circle.cpp \
        TP8/MinGL2/src/shape/line.cpp \
        TP8/MinGL2/src/shape/rectangle.cpp \
        TP8/MinGL2/src/shape/shape.cpp \
        TP8/MinGL2/src/shape/triangle.cpp \
        TP8/MinGL2/src/transition/transition.cpp \
        TP8/MinGL2/src/transition/transition_contract.cpp \
        TP8/MinGL2/src/transition/transition_engine.cpp \
        TP8/SFML/test.cpp \
        TP8/main.cpp \
        main.cpp

DISTFILES += \
    README.md \
    TP8/MinGL2/Doxyfile \
    TP8/MinGL2/README.md \
    TP8/MinGL2/examples/06-Sprite/res/doggo.si2 \
    TP8/MinGL2/examples/07-Audio/res/music.wav \
    TP8/MinGL2/examples/07-Audio/res/sound1.wav \
    TP8/MinGL2/examples/07-Audio/res/sound2.wav \
    TP8/MinGL2/examples/README.md \
    TP8/MinGL2/mingl.pri \
    TP8/MinGL2/tools/README.md \
    TP8/MinGL2/tools/img2si.py \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-all.pc \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-audio.pc \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-graphics.pc \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-network.pc \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-system.pc \
    TP8/SFML/lib/x86_64-linux-gnu/pkgconfig/sfml-window.pc \
    TP8/SFML/share/SFML/cmake/Modules/FindSFML.cmake \
    TP8/SFML/share/doc/libsfml-dev/README.Debian \
    TP8/SFML/share/doc/libsfml-dev/copyright

SUBDIRS += \
    TP8/MinGL2/examples/00-Boilerplate/00-Boilerplate.pro \
    TP8/MinGL2/examples/01-Shapes/01-Shapes.pro \
    TP8/MinGL2/examples/02-Texte/02-Texte.pro \
    TP8/MinGL2/examples/03-Clavier/03-Clavier.pro \
    TP8/MinGL2/examples/04-Souris/04-Souris.pro \
    TP8/MinGL2/examples/05-Transition/05-Transition.pro \
    TP8/MinGL2/examples/06-Sprite/06-Sprite.pro \
    TP8/MinGL2/examples/07-Audio/07-Audio.pro \
    TP8/MinGL2/examples/08-CustomDrawable/08-CustomDrawable.pro \
    TP8/MinGL2/examples/09-CustomTransitionable/09-CustomTransitionable.pro \
    TP8/MinGL2/mingl.pro \
    TP8/TP8.pro

HEADERS += \
    TP8/MinGL2/examples/08-CustomDrawable/bgtext.h \
    TP8/MinGL2/examples/09-CustomTransitionable/bgtext.h \
    TP8/MinGL2/include/mingl/audio/audioengine.h \
    TP8/MinGL2/include/mingl/event/event.hpp \
    TP8/MinGL2/include/mingl/event/event_manager.h \
    TP8/MinGL2/include/mingl/exception/cexception.h \
    TP8/MinGL2/include/mingl/exception/cexception.hpp \
    TP8/MinGL2/include/mingl/exception/errcode.h \
    TP8/MinGL2/include/mingl/graphics/idrawable.h \
    TP8/MinGL2/include/mingl/graphics/rgbacolor.h \
    TP8/MinGL2/include/mingl/graphics/vec2d.h \
    TP8/MinGL2/include/mingl/gui/glut_font.h \
    TP8/MinGL2/include/mingl/gui/sprite.h \
    TP8/MinGL2/include/mingl/gui/text.h \
    TP8/MinGL2/include/mingl/macros.h \
    TP8/MinGL2/include/mingl/mingl.h \
    TP8/MinGL2/include/mingl/shape/circle.h \
    TP8/MinGL2/include/mingl/shape/line.h \
    TP8/MinGL2/include/mingl/shape/rectangle.h \
    TP8/MinGL2/include/mingl/shape/shape.h \
    TP8/MinGL2/include/mingl/shape/triangle.h \
    TP8/MinGL2/include/mingl/tools/ieditable.h \
    TP8/MinGL2/include/mingl/tools/ieditable.hpp \
    TP8/MinGL2/include/mingl/tools/ifonctorunaire.hpp \
    TP8/MinGL2/include/mingl/transition/itransitionable.h \
    TP8/MinGL2/include/mingl/transition/transition.h \
    TP8/MinGL2/include/mingl/transition/transition_contract.h \
    TP8/MinGL2/include/mingl/transition/transition_engine.h \
    TP8/MinGL2/include/mingl/transition/transition_types.h \
    TP8/SFML/include/SFML/Audio.hpp \
    TP8/SFML/include/SFML/Audio/AlResource.hpp \
    TP8/SFML/include/SFML/Audio/Export.hpp \
    TP8/SFML/include/SFML/Audio/InputSoundFile.hpp \
    TP8/SFML/include/SFML/Audio/Listener.hpp \
    TP8/SFML/include/SFML/Audio/Music.hpp \
    TP8/SFML/include/SFML/Audio/OutputSoundFile.hpp \
    TP8/SFML/include/SFML/Audio/Sound.hpp \
    TP8/SFML/include/SFML/Audio/SoundBuffer.hpp \
    TP8/SFML/include/SFML/Audio/SoundBufferRecorder.hpp \
    TP8/SFML/include/SFML/Audio/SoundFileFactory.hpp \
    TP8/SFML/include/SFML/Audio/SoundFileFactory.inl \
    TP8/SFML/include/SFML/Audio/SoundFileReader.hpp \
    TP8/SFML/include/SFML/Audio/SoundFileWriter.hpp \
    TP8/SFML/include/SFML/Audio/SoundRecorder.hpp \
    TP8/SFML/include/SFML/Audio/SoundSource.hpp \
    TP8/SFML/include/SFML/Audio/SoundStream.hpp \
    TP8/SFML/include/SFML/Config.hpp \
    TP8/SFML/include/SFML/Graphics.hpp \
    TP8/SFML/include/SFML/Graphics/BlendMode.hpp \
    TP8/SFML/include/SFML/Graphics/CircleShape.hpp \
    TP8/SFML/include/SFML/Graphics/Color.hpp \
    TP8/SFML/include/SFML/Graphics/ConvexShape.hpp \
    TP8/SFML/include/SFML/Graphics/Drawable.hpp \
    TP8/SFML/include/SFML/Graphics/Export.hpp \
    TP8/SFML/include/SFML/Graphics/Font.hpp \
    TP8/SFML/include/SFML/Graphics/Glsl.hpp \
    TP8/SFML/include/SFML/Graphics/Glsl.inl \
    TP8/SFML/include/SFML/Graphics/Glyph.hpp \
    TP8/SFML/include/SFML/Graphics/Image.hpp \
    TP8/SFML/include/SFML/Graphics/PrimitiveType.hpp \
    TP8/SFML/include/SFML/Graphics/Rect.hpp \
    TP8/SFML/include/SFML/Graphics/Rect.inl \
    TP8/SFML/include/SFML/Graphics/RectangleShape.hpp \
    TP8/SFML/include/SFML/Graphics/RenderStates.hpp \
    TP8/SFML/include/SFML/Graphics/RenderTarget.hpp \
    TP8/SFML/include/SFML/Graphics/RenderTexture.hpp \
    TP8/SFML/include/SFML/Graphics/RenderWindow.hpp \
    TP8/SFML/include/SFML/Graphics/Shader.hpp \
    TP8/SFML/include/SFML/Graphics/Shape.hpp \
    TP8/SFML/include/SFML/Graphics/Sprite.hpp \
    TP8/SFML/include/SFML/Graphics/Text.hpp \
    TP8/SFML/include/SFML/Graphics/Texture.hpp \
    TP8/SFML/include/SFML/Graphics/Transform.hpp \
    TP8/SFML/include/SFML/Graphics/Transformable.hpp \
    TP8/SFML/include/SFML/Graphics/Vertex.hpp \
    TP8/SFML/include/SFML/Graphics/VertexArray.hpp \
    TP8/SFML/include/SFML/Graphics/View.hpp \
    TP8/SFML/include/SFML/Main.hpp \
    TP8/SFML/include/SFML/Network.hpp \
    TP8/SFML/include/SFML/Network/Export.hpp \
    TP8/SFML/include/SFML/Network/Ftp.hpp \
    TP8/SFML/include/SFML/Network/Http.hpp \
    TP8/SFML/include/SFML/Network/IpAddress.hpp \
    TP8/SFML/include/SFML/Network/Packet.hpp \
    TP8/SFML/include/SFML/Network/Socket.hpp \
    TP8/SFML/include/SFML/Network/SocketHandle.hpp \
    TP8/SFML/include/SFML/Network/SocketSelector.hpp \
    TP8/SFML/include/SFML/Network/TcpListener.hpp \
    TP8/SFML/include/SFML/Network/TcpSocket.hpp \
    TP8/SFML/include/SFML/Network/UdpSocket.hpp \
    TP8/SFML/include/SFML/OpenGL.hpp \
    TP8/SFML/include/SFML/System.hpp \
    TP8/SFML/include/SFML/System/Clock.hpp \
    TP8/SFML/include/SFML/System/Err.hpp \
    TP8/SFML/include/SFML/System/Export.hpp \
    TP8/SFML/include/SFML/System/FileInputStream.hpp \
    TP8/SFML/include/SFML/System/InputStream.hpp \
    TP8/SFML/include/SFML/System/Lock.hpp \
    TP8/SFML/include/SFML/System/MemoryInputStream.hpp \
    TP8/SFML/include/SFML/System/Mutex.hpp \
    TP8/SFML/include/SFML/System/NativeActivity.hpp \
    TP8/SFML/include/SFML/System/NonCopyable.hpp \
    TP8/SFML/include/SFML/System/Sleep.hpp \
    TP8/SFML/include/SFML/System/String.hpp \
    TP8/SFML/include/SFML/System/String.inl \
    TP8/SFML/include/SFML/System/Thread.hpp \
    TP8/SFML/include/SFML/System/Thread.inl \
    TP8/SFML/include/SFML/System/ThreadLocal.hpp \
    TP8/SFML/include/SFML/System/ThreadLocalPtr.hpp \
    TP8/SFML/include/SFML/System/ThreadLocalPtr.inl \
    TP8/SFML/include/SFML/System/Time.hpp \
    TP8/SFML/include/SFML/System/Utf.hpp \
    TP8/SFML/include/SFML/System/Utf.inl \
    TP8/SFML/include/SFML/System/Vector2.hpp \
    TP8/SFML/include/SFML/System/Vector2.inl \
    TP8/SFML/include/SFML/System/Vector3.hpp \
    TP8/SFML/include/SFML/System/Vector3.inl \
    TP8/SFML/include/SFML/Window.hpp \
    TP8/SFML/include/SFML/Window/Context.hpp \
    TP8/SFML/include/SFML/Window/ContextSettings.hpp \
    TP8/SFML/include/SFML/Window/Event.hpp \
    TP8/SFML/include/SFML/Window/Export.hpp \
    TP8/SFML/include/SFML/Window/GlResource.hpp \
    TP8/SFML/include/SFML/Window/Joystick.hpp \
    TP8/SFML/include/SFML/Window/Keyboard.hpp \
    TP8/SFML/include/SFML/Window/Mouse.hpp \
    TP8/SFML/include/SFML/Window/Sensor.hpp \
    TP8/SFML/include/SFML/Window/Touch.hpp \
    TP8/SFML/include/SFML/Window/VideoMode.hpp \
    TP8/SFML/include/SFML/Window/Window.hpp \
    TP8/SFML/include/SFML/Window/WindowHandle.hpp \
    TP8/SFML/include/SFML/Window/WindowStyle.hpp \
    space-const.h
